name: Publish to JSR

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x
      - name: Test
        run: deno test
      - name: Publish
        run: deno publish
